name: menpowidgets_rtd
channels:
  - menpo
dependencies:
  - python
  - setuptools

  - menpo>=0.7,<0.8
  - ipython>=4.*,<5.0
  - jupyter>=1.*,<2.0
  - ipywidgets>=4.1.1,<5.0
  - traitlets>=4.1,<5.0
  - pip:
      - sphinx
      - sphinx_rtd_theme
      - sphinxmapxrefrole>=0.2
